// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  boardId: __t.string().name("board_id"),
  laneId: __t.string().name("lane_id"),
  title: __t.string(),
  description: __t.string(),
  label: __t.string(),
  priority: __t.string(),
  assignee: __t.string(),
  dueDate: __t.string().name("due_date"),
  archived: __t.bool(),
  orderKey: __t.string().name("order_key"),
});
