// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  boardId: __t.string().name("board_id"),
  columnId: __t.string().name("column_id"),
  title: __t.string(),
  description: __t.string(),
  position: __t.f64(),
  label: __t.string(),
  priority: __t.string(),
  assignee: __t.string(),
  due: __t.string(),
  revision: __t.u32(),
  archived: __t.bool(),
  orderKey: __t.string().name("order_key"),
  moveVersion: __t.f64().name("move_version"),
  moveId: __t.string().name("move_id"),
});
