// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Board = __t.object("Board", {
  id: __t.string(),
  title: __t.string(),
  description: __t.string(),
  color: __t.string(),
});
export type Board = __Infer<typeof Board>;

export const Card = __t.object("Card", {
  id: __t.string(),
  boardId: __t.string(),
  columnId: __t.string(),
  title: __t.string(),
  description: __t.string(),
  position: __t.f64(),
  label: __t.string(),
  priority: __t.string(),
  assignee: __t.string(),
  due: __t.string(),
  revision: __t.u32(),
  archived: __t.bool(),
  orderKey: __t.string(),
  moveVersion: __t.f64(),
  moveId: __t.string(),
});
export type Card = __Infer<typeof Card>;

export const Column = __t.object("Column", {
  id: __t.string(),
  boardId: __t.string(),
  title: __t.string(),
  position: __t.f64(),
});
export type Column = __Infer<typeof Column>;

export const Comment = __t.object("Comment", {
  id: __t.string(),
  boardId: __t.string(),
  cardId: __t.string(),
  author: __t.string(),
  text: __t.string(),
  createdAt: __t.f64(),
});
export type Comment = __Infer<typeof Comment>;

export const Receipt = __t.object("Receipt", {
  id: __t.string(),
  boardId: __t.string(),
  actor: __t.string(),
  text: __t.string(),
  createdAt: __t.f64(),
});
export type Receipt = __Infer<typeof Receipt>;

export const RecentActivity = __t.object("RecentActivity", {});
export type RecentActivity = __Infer<typeof RecentActivity>;
