// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Activity = __t.object("Activity", {
  id: __t.string(),
  boardId: __t.string(),
  actor: __t.string(),
  text: __t.string(),
  createdAt: __t.f64(),
});
export type Activity = __Infer<typeof Activity>;

export const Board = __t.object("Board", {
  id: __t.string(),
  title: __t.string(),
  description: __t.string(),
  color: __t.string(),
});
export type Board = __Infer<typeof Board>;

export const Card = __t.object("Card", {
  id: __t.string(),
  boardId: __t.string(),
  laneId: __t.string(),
  title: __t.string(),
  description: __t.string(),
  label: __t.string(),
  priority: __t.string(),
  assignee: __t.string(),
  dueDate: __t.string(),
  archived: __t.bool(),
  orderKey: __t.string(),
});
export type Card = __Infer<typeof Card>;

export const Comment = __t.object("Comment", {
  id: __t.string(),
  boardId: __t.string(),
  cardId: __t.string(),
  author: __t.string(),
  text: __t.string(),
  createdAt: __t.f64(),
});
export type Comment = __Infer<typeof Comment>;

export const Lane = __t.object("Lane", {
  id: __t.string(),
  boardId: __t.string(),
  title: __t.string(),
  position: __t.f64(),
});
export type Lane = __Infer<typeof Lane>;

export const RecentActivity = __t.object("RecentActivity", {});
export type RecentActivity = __Infer<typeof RecentActivity>;

export const ReducerAck = __t.object("ReducerAck", {
  connectionId: __t.connectionId(),
  sequence: __t.u64(),
});
export type ReducerAck = __Infer<typeof ReducerAck>;
