// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCommentReducer from "../add_comment_reducer";
import ArchiveCardReducer from "../archive_card_reducer";
import CreateBoardReducer from "../create_board_reducer";
import CreateCardReducer from "../create_card_reducer";
import CreateLaneReducer from "../create_lane_reducer";
import DeleteBoardReducer from "../delete_board_reducer";
import DeleteCardReducer from "../delete_card_reducer";
import DeleteLaneReducer from "../delete_lane_reducer";
import EditBoardReducer from "../edit_board_reducer";
import EditCardReducer from "../edit_card_reducer";
import MoveCardReducer from "../move_card_reducer";
import RenameLaneReducer from "../rename_lane_reducer";

export type AddCommentParams = __Infer<typeof AddCommentReducer>;
export type ArchiveCardParams = __Infer<typeof ArchiveCardReducer>;
export type CreateBoardParams = __Infer<typeof CreateBoardReducer>;
export type CreateCardParams = __Infer<typeof CreateCardReducer>;
export type CreateLaneParams = __Infer<typeof CreateLaneReducer>;
export type DeleteBoardParams = __Infer<typeof DeleteBoardReducer>;
export type DeleteCardParams = __Infer<typeof DeleteCardReducer>;
export type DeleteLaneParams = __Infer<typeof DeleteLaneReducer>;
export type EditBoardParams = __Infer<typeof EditBoardReducer>;
export type EditCardParams = __Infer<typeof EditCardReducer>;
export type MoveCardParams = __Infer<typeof MoveCardReducer>;
export type RenameLaneParams = __Infer<typeof RenameLaneReducer>;
