// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCommentReducer from "../add_comment_reducer";
import ArchiveCardReducer from "../archive_card_reducer";
import CreateBoardReducer from "../create_board_reducer";
import CreateCardReducer from "../create_card_reducer";
import CreateColumnReducer from "../create_column_reducer";
import DeleteBoardReducer from "../delete_board_reducer";
import DeleteCardReducer from "../delete_card_reducer";
import DeleteColumnReducer from "../delete_column_reducer";
import EditCardReducer from "../edit_card_reducer";
import MoveCardReducer from "../move_card_reducer";
import RenameBoardReducer from "../rename_board_reducer";
import RenameColumnReducer from "../rename_column_reducer";

export type AddCommentParams = __Infer<typeof AddCommentReducer>;
export type ArchiveCardParams = __Infer<typeof ArchiveCardReducer>;
export type CreateBoardParams = __Infer<typeof CreateBoardReducer>;
export type CreateCardParams = __Infer<typeof CreateCardReducer>;
export type CreateColumnParams = __Infer<typeof CreateColumnReducer>;
export type DeleteBoardParams = __Infer<typeof DeleteBoardReducer>;
export type DeleteCardParams = __Infer<typeof DeleteCardReducer>;
export type DeleteColumnParams = __Infer<typeof DeleteColumnReducer>;
export type EditCardParams = __Infer<typeof EditCardReducer>;
export type MoveCardParams = __Infer<typeof MoveCardReducer>;
export type RenameBoardParams = __Infer<typeof RenameBoardReducer>;
export type RenameColumnParams = __Infer<typeof RenameColumnReducer>;
